dpkg-deb -bZgzip projects/AppSyncUnified debs
dpkg-deb -bZgzip projects/LoveIsAgain debs
dpkg-deb -bZgzip projects/Down debs
dpkg-deb -bZgzip projects/Failsafe debs
dpkg-deb -bZgzip projects/IAPCrazy debs
dpkg-deb -bZgzip projects/KGPayphone debs
dpkg-deb -bZgzip projects/LocalIAPStore debs
dpkg-deb -bZgzip projects/TweakModeNC debs
dpkg-deb -bZgzip projects/Hayah debs
dpkg-deb -bZgzip projects/MJKaman debs
dpkg-deb -bZgzip projects/iOS6 debs
dpkg-deb -bZgzip projects/LobsterTwo debs