dpkg-deb -bZgzip projects/AppSyncUnified debs
dpkg-deb -bZgzip projects/LoveIsAgain debs
dpkg-deb -bZgzip projects/CyDown debs
dpkg-deb -bZgzip projects/Failsafe debs
dpkg-deb -bZgzip projects/IAPCrazy debs
dpkg-deb -bZgzip projects/KGPayphone debs
dpkg-deb -bZgzip projects/LocalIAPStore debs
dpkg-deb -bZgzip projects/SnapCrack debs
dpkg-deb -bZgzip projects/TweakMode debs
dpkg-deb -bZgzip projects/Hayah debs
dpkg-deb -bZgzip projects/iOS6 debs